version: '3.7'

services:
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    restart: always

  server:
    image: bee1162/popcornmate-dev:latest
    container_name: server
    hostname: server
    depends_on:
      - redis
    env_file:
      - .env
    environment:
      - TZ=Asia/Seoul
    expose:
      - 8080

  nginx:
    depends_on:
      - server
    restart: always
    build:
      dockerfile: Dockerfile
      context: './nginx'
    ports:
      - "80:80"
  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    
