version: '3.7'

services:
  redis:
    image: redis
    container_name: redis
    hostname: redis
    ports:
      - "6379:6379"

  mysql:
    image: mysql
    container_name: mysql
    hostname: mysql
    volumes:
      - ./mysqldata:/var/lib/mysql
    environment:
      - MYSQL_USER=user
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_HOST=localhost
      - MYSQL_PORT=3307
    ports:
      - "3307:3306"