---
spring:
  config:
    activate:
      on-profile: local

  data:
    redis:
      host: localhost
      port: 6379
---
spring:
  config:
    activate:
      on-profile: dev

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT:6379}

#cloud:
#  aws:
#    s3:
#      bucket:
#    credentials:
#      access-key:
#      secret-key:
#    region:
#      static: ap-northeast-2
#      auto: false
#    stack:
#      auto: false
---
