---
spring:
  config:
    activate:
      on-profile: local,test

  data:
    redis:
      host: localhost
      port: 6379
cloud:
  aws:
    s3:
      bucket: popcornmate-bucket
    credentials:
      access-key: ${S3_ACCESS}
      secret-key: ${S3_SECRET}
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false

app:
  firebase-configuration-file: popcornmate-d7ca1-firebase-adminsdk-svbpw-343677f710.json

test:
  port:
    localhost

feign:
  httpclient:
    enabled: true


---
spring:
  config:
    activate:
      on-profile: dev

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT:6379}

cloud:
  aws:
    s3:
      bucket: popcornmate-bucket
    credentials:
      access-key: ${S3_ACCESS}
      secret-key: ${S3_SECRET}
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false

app:
  firebase-configuration-file: popcornmateprod-firebase-adminsdk-yvb81-02b4302a03.json
---
