server:
  servlet:
    context-path: /api
  forward-headers-strategy: framework

spring:
  profiles:
    include:
      - domain
      - core
      - infra
      - batch
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 5MB

springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    tags-sorter: alpha

app:
  tmdb: ${TMDB_SECRET}

---
spring:
  config:
    activate:
      on-profile: dev