# jwt 설정
auth:
  jwt:
    secret-key: ${JWT_SECRET_KEY}
    access-exp: ${JWT_ACCESS_EXP:3600}
    refresh-exp: ${JWT_REFRESH_TOKEN_EXP}

oauth:
  kakao:
    base-url: ${KAKAO_BASE_URL}
    client-id: ${KAKAO_CLIENT}
    client-secret: ${KAKAO_SECRET}
    redirect-url: ${KAKAO_REDIRECT}
    app-id: ${KAKAO_APP_ID}
    admin-key: ${KAKAO_ADMIN_KEY}
    web-client-id: ${KAKAO_WEB_CLIENT}
    web-app-id: ${KAKAO_WEB_APP_ID}

  apple:
    baseUrl: ${APPLE_BASE_URL}
    clientId: ${APPLE_CLIENT_ID}
    webClientId: ${APPLE_WEB_CLIENT_ID}
    keyId: ${APPLE_KEY_ID}
    redirectUrl: ${APPLE_REDIRECT}
    teamId: ${APPLE_TEAM_ID}
    webCallbackUrl: ${APPLE_WEB_CALLBACK}
    authKey: ${APPLE_AUTH_KEY}